### ISSUE TITLE
Plugin not working on intellij IDEA 2021.3

### ISSUE THREAD

**Issue by pineapplehunter** [easysoc/easysoc-chisel#1]
After upgrading my IDE, I got a message saying the plugin is not compatible.

some information
 * Intellij IDEA 2021.3 (Ultimate Edition) Build #IU-213.5744.223, built on November 27, 2021
 * OS: Linux (Ubuntu 20.04)
 * JDK: openjdk version "17.0.1"

Can the plugin be updated to support the newer IDE?
Thanks!

**Comment by itviewer** [comment]
Since there are very few users of this plugin, I plan that 2021.2 is the last supported version and will no longer support 2021.3 and later versions.

**Comment by pineapplehunter** [comment]
That sounds fine.
Have a nice holiday!
